name: CI/CD Pipeline

on:
  push:
    branches: [ rewrite ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  update-changelogs:
    if: ${{ contains(github.event.head_commit.message, ':bookmark:') }}
    uses: ./.github/workflows/update-changelogs.yml

  maven-release:
    needs: [ build, update-changelogs ]
    uses: ./.github/workflows/maven-release.yml
    secrets: inherit
