name: 'Update Changelogs'

on:
  workflow_call: { }

jobs:
  update-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          # This is needed for the scripts
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Give permissions to script
        run: chmod +x scripts/UpdateChangelogs

      - name: Run script
        run: java --source 21 ./scripts/UpdateChangelogs


