name: 'Update Changelogs'

on:
  workflow_call: { }

jobs:
  update-changelogs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Give permissions to script
        run: chmod +x scripts/UpdateChangelogs

      - name: Run script
        run: ./scripts/UpdateChangelogs


